### ISSUE TITLE
Can't determine minutes file

### ISSUE THREAD

**Issue by hancush** [datamade/scrapers-us-municipal#68]
```
[2022-08-24 04:50:20,533] {docker.py:263} INFO - 08/23/2022 23:50:20 INFO scrapelib: GET - http://webapi.legistar.com/v1/metro/matters/
[2022-08-24 04:50:21,494] {docker.py:263} INFO - 08/23/2022 23:50:21 INFO scrapelib: GET - http://webapi.legistar.com/v1/metro/matters/8758/attachments
[2022-08-24 04:50:22,447] {docker.py:263} INFO - Traceback (most recent call last):
[2022-08-24 04:50:22,448] {docker.py:263} INFO - File "/app/lametro/events.py", line 462, in find_approved_minutes
[2022-08-24 04:50:22,450] {docker.py:263} INFO - each for each in attachments
ValueError: too many values to unpack (expected 1)
[2022-08-24 04:50:22,450] {docker.py:263} INFO - During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pupa", line 8, in <module>
[2022-08-24 04:50:22,450] {docker.py:263} INFO - sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/pupa/cli/__main__.py", line 68, in main
[2022-08-24 04:50:22,450] {docker.py:263} INFO - subcommands[args.subcommand].handle(args, other)
  File "/usr/local/lib/python3.6/site-packages/pupa/cli/commands/update.py", line 278, in handle
[2022-08-24 04:50:22,451] {docker.py:263} INFO - return self.do_handle(args, other, juris)
  File "/usr/local/lib/python3.6/site-packages/pupa/cli/commands/update.py", line 327, in do_handle
[2022-08-24 04:50:22,451] {docker.py:263} INFO - report['scrape'] = self.do_scrape(juris, args, scrapers)
  File "/usr/local/lib/python3.6/site-packages/pupa/cli/commands/update.py", line 175, in do_scrape
[2022-08-24 04:50:22,451] {docker.py:263} INFO - report[scraper_name] = scraper.do_scrape(**scrape_args)
[2022-08-24 04:50:22,451] {docker.py:263} INFO - File "/usr/local/lib/python3.6/site-packages/pupa/scrape/base.py", line 114, in do_scrape
[2022-08-24 04:50:22,451] {docker.py:263} INFO - for obj in self.scrape(**kwargs) or []:
  File "/app/lametro/events.py", line 318, in scrape
[2022-08-24 04:50:22,451] {docker.py:263} INFO - approved_minutes = self.find_approved_minutes(event)
  File "/app/lametro/events.py", line 467, in find_approved_minutes
[2022-08-24 04:50:22,451] {docker.py:263} INFO - "More than one attachment for the approved minutes matter"
[2022-08-24 04:50:22,451] {docker.py:263} INFO - ValueError: More than one attachment for the approved minutes matter
```

**Comment by hancush** [comment]
Related to https://github.com/datamade/la-metro-councilmatic/issues/742
